## Vectorization

Using ONE HOT ENCODING 
It is type of text vectorization where we convert text -> vectors such thta every unique word has its correcsponding vector

We have seen it already

So we procedding with

## BAG OF WORDS
It creates array as per number of occurence of that unique word
shape will be same because every sentence vectorization inclines to vocabulary
If out of vocabulary still u cann proceed without error

In bag of words no meaning is interpreted in terms of sequence of words


In [23]:
from sklearn.feature_extraction.text import CountVectorizer

In [24]:
import pandas as pd

In [25]:
df = pd.DataFrame(
    {'col': ['People Love AI', 'AI Love Data', 'Data Love Love', 'Love People People']}
)

In [26]:
cv = CountVectorizer()

In [27]:
df

,col
0,People Love AI
1,AI Love Data
2,Data Love Love
3,Love People People


In [28]:
cv.fit_transform(df.col).toarray()

array([[1, 0, 1, 1],
       [1, 1, 1, 0],
       [0, 1, 2, 0],
       [0, 0, 1, 2]])

In [29]:
cv.vocabulary_

{'people': 3, 'love': 2, 'ai': 0, 'data': 1}

## N-Grams -> We take sequence of word in vocabulary i.e. It is a sequence of N consecutive words/tokens from a sentence.
Here we have bigram and trigram depends on the value of sequence like we take 2 sequence in bigram and 3 in trigram
sentence = w1 w2 w3 w4

bigram => w1w2 w2w3 w3w4
trigram => w1w2w3 w2w3w4
4-gram => w1w2w3w4

In [40]:
cv = CountVectorizer(ngram_range=(1, 2))

cv.fit_transform(df.col).toarray()

array([[1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0],
       [1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 2, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 1, 2, 0, 1]])

In [41]:
cv.vocabulary_

{'people': 9,
 'love': 4,
 'ai': 0,
 'people love': 10,
 'love ai': 5,
 'data': 2,
 'ai love': 1,
 'love data': 6,
 'data love': 3,
 'love love': 7,
 'love people': 8,
 'people people': 11}

In [43]:
## Bigram => 8
## unigram => 4
## trigram => 4
## unigram + Bigram => 12

## TF-IDF
#### How important is this word to this document compared with the whole collection
#### TF-IDF = Term Frequency × Inverse Document Frequency

TF → Term Frequency
How frequently does a word appear inside one document?
TF = Number of times term appears
     ─────────────────────────────
     Total number of terms

IDF → Inverse Document Frequency
How rare/common is that word across all documents?
IDF = log(N / DF)
Where
N = total number of documents
DF = number of documents containing the term**

In [53]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [46]:
tf = TfidfVectorizer()

In [48]:
tf.fit_transform(df.col).toarray()

array([[0.64043405, 0.        , 0.42389674, 0.64043405],
       [0.64043405, 0.64043405, 0.42389674, 0.        ],
       [0.        , 0.60276058, 0.7979221 , 0.        ],
       [0.        , 0.        , 0.31418628, 0.94936136]])

In [49]:
tf.vocabulary_

{'people': 3, 'love': 2, 'ai': 0, 'data': 1}

In [51]:
tf.get_feature_names_out()

array(['ai', 'data', 'love', 'people'], dtype=object)

In [52]:
tf.idf_

array([1.51082562, 1.51082562, 1.        , 1.51082562])

# Word2Vec

#### DL Architecture Algo

In [1]:
pip install gensim

   ---------------------------------------- 0.0/24.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/24.4 MB 682.7 kB/s eta 0:00:36
   ---------------------------------------- 0.1/24.4 MB 1.8 MB/s eta 0:00:14
   ---------------------------------------- 0.3/24.4 MB 2.5 MB/s eta 0:00:10
    --------------------------------------- 0.5/24.4 MB 3.2 MB/s eta 0:00:08
   - -------------------------------------- 0.7/24.4 MB 3.2 MB/s eta 0:00:08
   - -------------------------------------- 0.9/24.4 MB 3.5 MB/s eta 0:00:07
   - -------------------------------------- 1.2/24.4 MB 4.0 MB/s eta 0:00:06
   -- ------------------------------------- 1.5/24.4 MB 4.3 MB/s eta 0:00:06
   -- ------------------------------------- 1.8/24.4 MB 4.5 MB/s eta 0:00:05
   --- ------------------------------------ 2.1/24.4 MB 4.7 MB/s eta 0:00:05
   --- ------------------------------------ 2.3/24.4 MB 4.6 MB/s eta 0:00:05
   ---- ----------------------------------- 2.7/24.4 MB 5.1 MB/s eta 0:00:05
   -


[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import gensim

In [3]:
from gensim.models import KeyedVectors

In [4]:
path = r"C:\Users\ManishAgrahari\Downloads\GoogleNews-vectors-negative300.bin\GoogleNews-vectors-negative300.bin"

In [6]:
model = KeyedVectors.load_word2vec_format(path, binary=True, limit=200000)

In [7]:
model['man']

array([ 0.32617188,  0.13085938,  0.03466797, -0.08300781,  0.08984375,
       -0.04125977, -0.19824219,  0.00689697,  0.14355469,  0.0019455 ,
        0.02880859, -0.25      , -0.08398438, -0.15136719, -0.10205078,
        0.04077148, -0.09765625,  0.05932617,  0.02978516, -0.10058594,
       -0.13085938,  0.001297  ,  0.02612305, -0.27148438,  0.06396484,
       -0.19140625, -0.078125  ,  0.25976562,  0.375     , -0.04541016,
        0.16210938,  0.13671875, -0.06396484, -0.02062988, -0.09667969,
        0.25390625,  0.24804688, -0.12695312,  0.07177734,  0.3203125 ,
        0.03149414, -0.03857422,  0.21191406, -0.00811768,  0.22265625,
       -0.13476562, -0.07617188,  0.01049805, -0.05175781,  0.03808594,
       -0.13378906,  0.125     ,  0.0559082 , -0.18261719,  0.08154297,
       -0.08447266, -0.07763672, -0.04345703,  0.08105469, -0.01092529,
        0.17480469,  0.30664062, -0.04321289, -0.01416016,  0.09082031,
       -0.00927734, -0.03442383, -0.11523438,  0.12451172, -0.02

In [46]:
model['king']

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

## Arithmetic Operation with model

In [9]:
model['king'] - model['queen']

array([ 1.20727539e-01,  1.73339844e-01,  7.79418945e-02,  1.61132812e-02,
       -1.57470703e-01,  5.27343750e-02,  1.83105469e-01,  1.85546875e-02,
        2.48535156e-01,  3.07617188e-01, -1.66503906e-01,  7.81250000e-02,
       -2.81738281e-01, -2.40859985e-02, -3.00781250e-01, -2.82714844e-01,
       -3.80859375e-02,  5.20935059e-02, -1.95312500e-02,  3.46679688e-02,
       -5.37109375e-02, -2.39257812e-02,  2.95898438e-01,  2.55371094e-01,
        3.56445312e-02, -1.23535156e-01,  5.66406250e-02, -3.19824219e-02,
        1.53320312e-01,  1.35864258e-01,  2.60742188e-01,  1.92626953e-01,
        2.07031250e-01,  1.87500000e-01,  3.32031250e-02,  2.15820312e-01,
       -5.71289062e-02, -2.57812500e-01,  1.65039062e-01, -1.07421875e-02,
        3.17382812e-02,  1.84570312e-01,  1.36718750e-02,  1.70288086e-01,
        1.66015625e-01,  8.88671875e-02, -1.05743408e-01, -1.12304688e-01,
       -2.10937500e-01, -2.52258301e-01, -1.44165039e-01,  5.95703125e-02,
       -3.12744141e-01,  

In [30]:
model.similarity('happy', 'joyful')

np.float32(0.42381963)

In [36]:
model.doesnt_match(['PHP', 'Java', 'Python', 'Snake'])

'Snake'

In [37]:
model.most_similar('cricket')

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819188117981),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.75413978099823),
 ('cricketer', 0.7372578382492065),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.6987985968589783),
 ('Cricket_Board', 0.687838613986969)]

In [40]:
model.most_similar('king')

[('kings', 0.7138045430183411),
 ('queen', 0.6510956883430481),
 ('monarch', 0.6413194537162781),
 ('crown_prince', 0.6204220056533813),
 ('prince', 0.6159993410110474),
 ('sultan', 0.5864824056625366),
 ('ruler', 0.5797567367553711),
 ('princes', 0.5646552443504333),
 ('throne', 0.5422105193138123),
 ('royal', 0.5239794254302979)]

In [43]:
vec = model['king'] - model['man'] + model['women']
model.most_similar(vec)

[('king', 0.6478992700576782),
 ('queen', 0.535493791103363),
 ('women', 0.5233659148216248),
 ('kings', 0.5162314772605896),
 ('queens', 0.4995364248752594),
 ('princes', 0.46233269572257996),
 ('monarch', 0.45280295610427856),
 ('monarchy', 0.4293173849582672),
 ('crown_prince', 0.42302510142326355),
 ('concubines', 0.4224807024002075)]

In [54]:
v = model['old'] + model['new']
model.most_similar(v)

[('old', 0.8359463810920715),
 ('new', 0.7212511897087097),
 ('yearold', 0.5905300974845886),
 ('boy', 0.44525524973869324),
 ('next', 0.4311877489089966),
 ('olds', 0.42996662855148315),
 ('young', 0.42929893732070923),
 ('newest', 0.42861050367355347),
 ('younger', 0.4268770217895508),
 ('older', 0.4186960458755493)]

## The underlying assumptions of word2vec is that words that are used in similar context shares the similar meaning and hence are provided with similar vectors

### For eg
#### sent1 = i like to watch cricket
#### sent1 = i like to watch football

#### for cricket and football context is same so it will provided with nearly similar vector embedding

#### It has 2 types:
#### CBOW
#### Skipgram

y = x1w1 + x2w2 + x3w3 + b => DL algorithm