## Vectorization

Using ONE HOT ENCODING 
It is type of text vectorization where we convert text -> vectors such thta every unique word has its correcsponding vector

We have seen it already

So we procedding with

## BAG OF WORDS
It creates array as per number of occurence of that unique word
shape will be same because every sentence vectorization inclines to vocabulary
If out of vocabulary still u cann proceed without error

In bag of words no meaning is interpreted in terms of sequence of words


In [2]:
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
import pandas as pd

In [4]:
df = pd.DataFrame(
    {'col': ['People Love AI', 'AI Love Data', 'Data Love Love', 'Love People People']}
)

In [5]:
cv = CountVectorizer()

In [6]:
df

,col
0,People Love AI
1,AI Love Data
2,Data Love Love
3,Love People People


In [7]:
cv.fit_transform(df.col).toarray()

array([[1, 0, 1, 1],
       [1, 1, 1, 0],
       [0, 1, 2, 0],
       [0, 0, 1, 2]])

In [8]:
cv.vocabulary_

{'people': 3, 'love': 2, 'ai': 0, 'data': 1}

## N-Grams -> We take sequence of word in vocabulary i.e. It is a sequence of N consecutive words/tokens from a sentence.
Here we have bigram and trigram depends on the value of sequence like we take 2 sequence in bigram and 3 in trigram
sentence = w1 w2 w3 w4

bigram => w1w2 w2w3 w3w4
trigram => w1w2w3 w2w3w4
4-gram => w1w2w3w4

In [9]:
cv = CountVectorizer(ngram_range=(1, 2))

cv.fit_transform(df.col).toarray()

array([[1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0],
       [1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 2, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 1, 2, 0, 1]])

In [10]:
cv.vocabulary_

{'people': 9,
 'love': 4,
 'ai': 0,
 'people love': 10,
 'love ai': 5,
 'data': 2,
 'ai love': 1,
 'love data': 6,
 'data love': 3,
 'love love': 7,
 'love people': 8,
 'people people': 11}

In [11]:
## Bigram => 8
## unigram => 4
## trigram => 4
## unigram + Bigram => 12

## TF-IDF
#### How important is this word to this document compared with the whole collection
#### TF-IDF = Term Frequency × Inverse Document Frequency

TF → Term Frequency
How frequently does a word appear inside one document?
TF = Number of times term appears
     ─────────────────────────────
     Total number of terms

IDF → Inverse Document Frequency
How rare/common is that word across all documents?
IDF = log(N / DF)
Where
N = total number of documents
DF = number of documents containing the term**

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [13]:
tf = TfidfVectorizer()

In [14]:
tf.fit_transform(df.col).toarray()

array([[0.64043405, 0.        , 0.42389674, 0.64043405],
       [0.64043405, 0.64043405, 0.42389674, 0.        ],
       [0.        , 0.60276058, 0.7979221 , 0.        ],
       [0.        , 0.        , 0.31418628, 0.94936136]])

In [15]:
tf.vocabulary_

{'people': 3, 'love': 2, 'ai': 0, 'data': 1}

In [16]:
tf.get_feature_names_out()

array(['ai', 'data', 'love', 'people'], dtype=object)

In [17]:
tf.idf_

array([1.51082562, 1.51082562, 1.        , 1.51082562])

# Word2Vec

#### DL Architecture Algo

In [18]:
pip install gensim

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [19]:
import gensim

In [20]:
from gensim.models import KeyedVectors

In [21]:
path = r"C:\Users\ManishAgrahari\Downloads\GoogleNews-vectors-negative300.bin\GoogleNews-vectors-negative300.bin"

In [22]:
model = KeyedVectors.load_word2vec_format(path, binary=True, limit=200000)

In [23]:
model['man']

array([ 0.32617188,  0.13085938,  0.03466797, -0.08300781,  0.08984375,
       -0.04125977, -0.19824219,  0.00689697,  0.14355469,  0.0019455 ,
        0.02880859, -0.25      , -0.08398438, -0.15136719, -0.10205078,
        0.04077148, -0.09765625,  0.05932617,  0.02978516, -0.10058594,
       -0.13085938,  0.001297  ,  0.02612305, -0.27148438,  0.06396484,
       -0.19140625, -0.078125  ,  0.25976562,  0.375     , -0.04541016,
        0.16210938,  0.13671875, -0.06396484, -0.02062988, -0.09667969,
        0.25390625,  0.24804688, -0.12695312,  0.07177734,  0.3203125 ,
        0.03149414, -0.03857422,  0.21191406, -0.00811768,  0.22265625,
       -0.13476562, -0.07617188,  0.01049805, -0.05175781,  0.03808594,
       -0.13378906,  0.125     ,  0.0559082 , -0.18261719,  0.08154297,
       -0.08447266, -0.07763672, -0.04345703,  0.08105469, -0.01092529,
        0.17480469,  0.30664062, -0.04321289, -0.01416016,  0.09082031,
       -0.00927734, -0.03442383, -0.11523438,  0.12451172, -0.02

In [24]:
model['king']

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

## Arithmetic Operation with model

In [25]:
model['king'] - model['queen']

array([ 1.20727539e-01,  1.73339844e-01,  7.79418945e-02,  1.61132812e-02,
       -1.57470703e-01,  5.27343750e-02,  1.83105469e-01,  1.85546875e-02,
        2.48535156e-01,  3.07617188e-01, -1.66503906e-01,  7.81250000e-02,
       -2.81738281e-01, -2.40859985e-02, -3.00781250e-01, -2.82714844e-01,
       -3.80859375e-02,  5.20935059e-02, -1.95312500e-02,  3.46679688e-02,
       -5.37109375e-02, -2.39257812e-02,  2.95898438e-01,  2.55371094e-01,
        3.56445312e-02, -1.23535156e-01,  5.66406250e-02, -3.19824219e-02,
        1.53320312e-01,  1.35864258e-01,  2.60742188e-01,  1.92626953e-01,
        2.07031250e-01,  1.87500000e-01,  3.32031250e-02,  2.15820312e-01,
       -5.71289062e-02, -2.57812500e-01,  1.65039062e-01, -1.07421875e-02,
        3.17382812e-02,  1.84570312e-01,  1.36718750e-02,  1.70288086e-01,
        1.66015625e-01,  8.88671875e-02, -1.05743408e-01, -1.12304688e-01,
       -2.10937500e-01, -2.52258301e-01, -1.44165039e-01,  5.95703125e-02,
       -3.12744141e-01,  

In [26]:
model.similarity('happy', 'joyful')

np.float32(0.42381963)

In [27]:
model.doesnt_match(['PHP', 'Java', 'Python', 'Snake'])

'Snake'

In [28]:
model.most_similar('cricket')

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819188117981),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.75413978099823),
 ('cricketer', 0.7372578382492065),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.6987985968589783),
 ('Cricket_Board', 0.687838613986969)]

In [29]:
model.most_similar('king')

[('kings', 0.7138045430183411),
 ('queen', 0.6510956883430481),
 ('monarch', 0.6413194537162781),
 ('crown_prince', 0.6204220056533813),
 ('prince', 0.6159993410110474),
 ('sultan', 0.5864824056625366),
 ('ruler', 0.5797567367553711),
 ('princes', 0.5646552443504333),
 ('throne', 0.5422105193138123),
 ('royal', 0.5239794254302979)]

In [30]:
vec = model['king'] - model['man'] + model['women']
model.most_similar(vec)

[('king', 0.6478992700576782),
 ('queen', 0.535493791103363),
 ('women', 0.5233659148216248),
 ('kings', 0.5162314772605896),
 ('queens', 0.4995364248752594),
 ('princes', 0.46233269572257996),
 ('monarch', 0.45280295610427856),
 ('monarchy', 0.4293173849582672),
 ('crown_prince', 0.42302510142326355),
 ('concubines', 0.4224807024002075)]

In [31]:
v = model['old'] + model['new']
model.most_similar(v)

[('old', 0.8359463810920715),
 ('new', 0.7212511897087097),
 ('yearold', 0.5905300974845886),
 ('boy', 0.44525524973869324),
 ('next', 0.4311877489089966),
 ('olds', 0.42996662855148315),
 ('young', 0.42929893732070923),
 ('newest', 0.42861050367355347),
 ('younger', 0.4268770217895508),
 ('older', 0.4186960458755493)]

## The underlying assumptions of word2vec is that words that are used in similar context shares the similar meaning and hence are provided with similar vectors

### For eg
#### sent1 = i like to watch cricket
#### sent1 = i like to watch football

#### for cricket and football context is same so it will provided with nearly similar vector embedding

#### It has 2 types:
#### CBOW
#### Skipgram

y = x1w1 + x2w2 + x3w3 + b => DL algorithm

## Back Propagation and Activation Fn => We do back propagation only when we didint get the predicted valuse as needed or required

## Going to train word2vec model on presonal data

In [32]:
with open('J. K. Rowling - Harry Potter 1 - Sorcerer Stone.txt', 'rt') as b1:
    h1 = b1.read()

with open('J. K. Rowling - Harry Potter 2 - The Chamber Of Secrets.txt', 'rt') as b2:
    h2 = b2.read()

with open('J. K. Rowling - Harry Potter 3 - Prisoner of Azkaban.txt', 'rt') as b3:
    h3 = b3.read()

with open('J. K. Rowling - Harry Potter 4 - The Goblet of Fire.txt', 'rt') as b4:
    h4 = b4.read()

In [33]:
data = h1 + h2 + h3 + h4

In [34]:
len(data)

2652652

In [35]:
len(data.split()) ## Total number of words in Harry Potter Data corpus

467490

In [36]:
## Applying NLP preprocessing 

## Tokenization -> Sentence Tokenization
## Stop word Removal 
## Lower casing

from gensim.utils import simple_preprocess
from nltk.tokenize import sent_tokenize

In [37]:
potter = []
data = sent_tokenize(data)

In [38]:
for i in data:
    potter.append(simple_preprocess(i))

In [39]:
potter

[['harry',
  'potter',
  'and',
  'the',
  'sorcerer',
  'stone',
  'chapter',
  'one',
  'the',
  'boy',
  'who',
  'lived',
  'mr',
  'and',
  'mrs',
  'dursley',
  'of',
  'number',
  'four',
  'privet',
  'drive',
  'were',
  'proud',
  'to',
  'say',
  'that',
  'they',
  'were',
  'perfectly',
  'normal',
  'thank',
  'you',
  'very',
  'much'],
 ['they',
  'were',
  'the',
  'last',
  'people',
  'you',
  'expect',
  'to',
  'be',
  'involved',
  'in',
  'anything',
  'strange',
  'or',
  'mysterious',
  'because',
  'they',
  'just',
  'didn',
  'hold',
  'with',
  'such',
  'nonsense'],
 ['mr',
  'dursley',
  'was',
  'the',
  'director',
  'of',
  'firm',
  'called',
  'grunnings',
  'which',
  'made',
  'drills'],
 ['he',
  'was',
  'big',
  'beefy',
  'man',
  'with',
  'hardly',
  'any',
  'neck',
  'although',
  'he',
  'did',
  'have',
  'very',
  'large',
  'mustache'],
 ['mrs',
  'dursley',
  'was',
  'thin',
  'and',
  'blonde',
  'and',
  'had',
  'nearly',
  'twice'

In [40]:
from nltk.corpus import stopwords

en_sw = set(stopwords.words('english'))
en_sw

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

In [41]:
def remove_stopwords(text):
    cleaned_text = []
    for sentence in text:
        cleaned_sentence = []
        for word in sentence:
            if word not in en_sw:
                cleaned_sentence.append(word)
        cleaned_text.append(cleaned_sentence)
    return cleaned_text


In [42]:
cleaned_potter = remove_stopwords(potter)
cleaned_potter

[['harry',
  'potter',
  'sorcerer',
  'stone',
  'chapter',
  'one',
  'boy',
  'lived',
  'mr',
  'mrs',
  'dursley',
  'number',
  'four',
  'privet',
  'drive',
  'proud',
  'say',
  'perfectly',
  'normal',
  'thank',
  'much'],
 ['last',
  'people',
  'expect',
  'involved',
  'anything',
  'strange',
  'mysterious',
  'hold',
  'nonsense'],
 ['mr',
  'dursley',
  'director',
  'firm',
  'called',
  'grunnings',
  'made',
  'drills'],
 ['big', 'beefy', 'man', 'hardly', 'neck', 'although', 'large', 'mustache'],
 ['mrs',
  'dursley',
  'thin',
  'blonde',
  'nearly',
  'twice',
  'usual',
  'amount',
  'neck',
  'came',
  'useful',
  'spent',
  'much',
  'time',
  'craning',
  'garden',
  'fences',
  'spying',
  'neighbors'],
 ['dursleys',
  'small',
  'son',
  'called',
  'dudley',
  'opinion',
  'finer',
  'boy',
  'anywhere'],
 ['dursleys',
  'everything',
  'wanted',
  'also',
  'secret',
  'greatest',
  'fear',
  'somebody',
  'would',
  'discover'],
 ['think', 'could', 'bear'

In [43]:
import gensim

model = gensim.models.Word2Vec(window=10, min_count=2)
model

In [44]:
model.build_vocab(cleaned_potter)

In [45]:
model.train(cleaned_potter, total_examples=model.corpus_count, epochs=model.epochs)

(1101853, 1224935)

In [46]:
model.wv['harry']

array([-0.35999146,  0.23842297,  0.17447047,  0.1574112 ,  0.01233758,
       -0.692335  ,  0.23853521,  1.069314  , -0.48275414, -0.36568698,
        0.08850452, -0.29279354, -0.03348199,  0.5949504 ,  0.3356162 ,
       -0.33481652,  0.445998  ,  0.17241363,  0.19081447, -0.6734875 ,
        0.24034674,  0.2141462 ,  0.55096745, -0.4660852 ,  0.60490197,
        0.02821532, -0.5506946 ,  0.10655055, -0.12051458, -0.1014682 ,
        0.5792675 ,  0.36774465, -0.33846796, -0.272569  , -0.61684453,
        0.67733496,  0.35803834, -0.6587619 , -0.29322645, -1.2401557 ,
       -0.5273321 , -0.32583266, -0.5494337 , -0.14292297,  0.2831232 ,
       -0.58234173, -0.3150623 , -0.1589993 , -0.00842025,  0.4326545 ,
        0.18094635, -0.14545147, -0.3630737 , -0.47625613, -0.03840553,
        0.01038995,  0.36196685, -0.1910342 , -0.6483167 ,  0.8698144 ,
        0.09235612,  0.10493651,  0.23151371,  0.03708623, -0.7635577 ,
        0.3665404 , -0.02021481,  0.5431    , -0.5164174 ,  1.05

In [47]:
len(model.wv['harry'])

100

In [48]:
model.wv['book']

array([-0.4872417 ,  0.23691961,  0.44384974, -0.2599676 , -0.05033155,
       -0.6132004 ,  0.29263484,  1.1730288 , -0.45840657, -0.26278993,
       -0.35345435, -0.5991704 , -0.32054657,  0.23191771,  0.21507268,
       -0.30604652,  0.18616226, -0.28220934,  0.44247177, -0.65069103,
        0.2836189 ,  0.33553326,  0.3133228 , -0.46909934,  0.40095714,
        0.08154466, -0.6544801 , -0.27937737, -0.06268292, -0.1405883 ,
        0.4490407 ,  0.34678656, -0.22196247, -0.29099873, -0.44187295,
        0.8645514 ,  0.18285683, -0.50759244, -0.39219564, -1.4116468 ,
       -0.22090927, -0.59129703, -0.34737262,  0.01417038,  0.38171074,
       -0.640052  , -0.25204238, -0.2969224 , -0.06358436,  0.22823526,
        0.26185322, -0.30784178, -0.03005707, -0.19033927, -0.32898435,
        0.21583661,  0.34963226, -0.11492772, -0.37776032,  0.7217468 ,
        0.04863835,  0.23874031, -0.10874219,  0.01345996, -0.51784337,
        0.29539692, -0.08257973,  0.15243047, -0.39045325,  0.76

In [49]:
model.wv.most_similar('harry')

[('quickly', 0.9608938694000244),
 ('slowly', 0.9603041410446167),
 ('grinning', 0.9595273733139038),
 ('pointing', 0.9594781994819641),
 ('nervously', 0.9593929648399353),
 ('peering', 0.9593139290809631),
 ('rubbing', 0.9587982892990112),
 ('curiously', 0.9576162695884705),
 ('slightly', 0.9545044898986816),
 ('staring', 0.9545028805732727)]

In [50]:
model.wv.most_similar('ron')

[('hermione', 0.9869841933250427),
 ('looking', 0.9614941477775574),
 ('quickly', 0.9560375809669495),
 ('harry', 0.9523141384124756),
 ('right', 0.948826789855957),
 ('peering', 0.9362744092941284),
 ('grinning', 0.9337022304534912),
 ('pointing', 0.9337015151977539),
 ('rubbing', 0.9328523874282837),
 ('nervously', 0.9319170713424683)]

In [51]:
model.wv.most_similar('neville')

[('amazement', 0.9971056580543518),
 ('gasped', 0.9967936873435974),
 ('ear', 0.9966774582862854),
 ('shocked', 0.9964588284492493),
 ('leaning', 0.9960350394248962),
 ('hissed', 0.9960314035415649),
 ('eagerly', 0.9960284233093262),
 ('ignoring', 0.995810866355896),
 ('anxiously', 0.9956950545310974),
 ('surprise', 0.9953136444091797)]

In [52]:
model.wv.most_similar('dumbledore')

[('grubbly', 0.9819223880767822),
 ('lupin', 0.9817162156105042),
 ('dippet', 0.9809969663619995),
 ('plank', 0.9754446744918823),
 ('flitwick', 0.9687482714653015),
 ('binns', 0.9649110436439514),
 ('sprout', 0.9630512595176697),
 ('trelawney', 0.9608121514320374),
 ('snape', 0.9600743651390076),
 ('vector', 0.954332709312439)]

In [53]:
model.wv.most_similar('fruit')

[('wings', 0.9958954453468323),
 ('several', 0.9958176016807556),
 ('hot', 0.9956728219985962),
 ('size', 0.9956116080284119),
 ('heavy', 0.9955947399139404),
 ('rain', 0.9955373406410217),
 ('inch', 0.9955077171325684),
 ('colored', 0.9954842925071716),
 ('bars', 0.9954321980476379),
 ('posts', 0.9953630566596985)]

In [54]:
model.wv.doesnt_match(['ron', 'hermoine', 'voldemort'])

'ron'

In [55]:
model.wv.doesnt_match(['harry', 'hermoine', 'ron'])

'ron'

In [56]:
model.wv.get_normed_vectors()

array([[-0.07868312,  0.05211197,  0.03813391, ..., -0.17770986,
         0.05525075,  0.0691715 ],
       [-0.06445199,  0.03380777,  0.08367579, ..., -0.09255993,
         0.05984348,  0.01677403],
       [-0.05887701,  0.04625698, -0.00304863, ..., -0.15325515,
         0.03417415,  0.02913154],
       ...,
       [ 0.03333354,  0.03412979,  0.06408025, ..., -0.20507647,
         0.00260733,  0.12164164],
       [-0.12335391,  0.07793011,  0.10718932, ..., -0.11269499,
         0.06895697,  0.03146244],
       [-0.1331539 ,  0.02710317,  0.07991198, ..., -0.1046663 ,
         0.04253209,  0.05443703]], shape=(9219, 100), dtype=float32)

In [57]:
y = model.wv.index_to_key

In [58]:
from sklearn.decomposition import PCA

pca = PCA(n_components=3)

In [59]:
x = pca.fit_transform(model.wv.get_normed_vectors())
x

array([[ 0.15422262,  0.20477915, -0.18917137],
       [-0.25232038,  0.42796755, -0.25072855],
       [ 0.12462203,  0.4137851 , -0.31664413],
       ...,
       [ 0.20168309,  0.35042778, -0.01545417],
       [-0.00445277,  0.07810485, -0.06719708],
       [ 0.06089921,  0.03101116,  0.01118243]],
      shape=(9219, 3), dtype=float32)

In [60]:
import plotly.io as pio

In [61]:
pio.renderers.default = 'browser'

In [62]:
import plotly.express as px

fig = px.scatter_3d(x[:100], x=0, y=1, z=2, color=y[:100])

fig.show()