In [1]:
import numpy as np

arr = np.array([1,2,3])
two_d = np.array([[1,2,3], [4,5,6], [7,8,9]])
three_d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]], [[13,14,15], [16,17,18]]])

In [201]:
arr.shape


(3, 3)

In [202]:
arr.ndim

2

In [203]:
arr.size

9

In [46]:
two_d.dtype

dtype('int64')

In [43]:
three_d.itemsize

8

In [16]:
range_data = np.arange(1, 17)
range_data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [17]:
arrange_data = range_data.reshape(4,4)
arrange_data

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [26]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
np.zeros((4, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.random.random((4, 5))

array([[0.28654106, 0.60741516, 0.30567657, 0.9506342 , 0.01564897],
       [0.42681968, 0.10557868, 0.20865533, 0.30442266, 0.98428135],
       [0.84371862, 0.24900224, 0.79769665, 0.12893746, 0.95186289],
       [0.33193029, 0.12870938, 0.44491595, 0.93562488, 0.54415699]])

In [31]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
np.linspace(-10, 10, 6)

array([-10.,  -6.,  -2.,   2.,   6.,  10.])

In [47]:
arr = np.arange(1, 17)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [48]:
arr.dtype

dtype('int64')

In [49]:
arr.astype('float64')

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16.])

In [66]:
arr = np.random.random((3, 3)) * 100
new_arr = np.round(arr)
int_arr = new_arr.astype("int32")
int_arr

array([[ 7,  1, 75],
       [95, 73, 75],
       [80, 72, 52]], dtype=int32)

In [67]:
int_arr + 2

array([[ 9,  3, 77],
       [97, 75, 77],
       [82, 74, 54]], dtype=int32)

In [68]:
int_arr > 60

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True, False]])

In [70]:
arr_1 = np.arange(1, 17).reshape(4, 4)
arr_2 = np.arange(17, 33).reshape(4, 4)

In [71]:
arr_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [72]:
arr_2

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [73]:
arr_1 + arr_2

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [74]:
arr_1 * arr_2

array([[ 17,  36,  57,  80],
       [105, 132, 161, 192],
       [225, 260, 297, 336],
       [377, 420, 465, 512]])

In [75]:
arr_2 - arr_1

array([[16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16]])

In [76]:
arr_1 - arr_2

array([[-16, -16, -16, -16],
       [-16, -16, -16, -16],
       [-16, -16, -16, -16],
       [-16, -16, -16, -16]])

In [77]:
arr_2 / arr_1

array([[17.        ,  9.        ,  6.33333333,  5.        ],
       [ 4.2       ,  3.66666667,  3.28571429,  3.        ],
       [ 2.77777778,  2.6       ,  2.45454545,  2.33333333],
       [ 2.23076923,  2.14285714,  2.06666667,  2.        ]])

In [85]:
np.min(arr_2)

np.int64(17)

In [91]:
array_data = np.round(np.random.random((4, 4)) * 100).astype("int")
array_data

array([[10, 11, 81, 42],
       [94, 60,  9, 74],
       [46, 18,  3, 41],
       [78, 68,  5, 59]])

In [93]:
np.max(array_data, axis=0)

array([94, 68, 81, 74])

In [94]:
np.max(array_data, axis=1)

array([81, 94, 46, 78])

In [97]:
np.sum(array_data, axis=0)

array([228, 157,  98, 216])

In [98]:
array_data

array([[10, 11, 81, 42],
       [94, 60,  9, 74],
       [46, 18,  3, 41],
       [78, 68,  5, 59]])

In [100]:
np.prod(arr_1, axis=1)

array([   24,  1680, 11880, 43680])

In [102]:
np.prod(array_data)

np.int64(-2274729193639897088)

In [103]:
array_data

array([[10, 11, 81, 42],
       [94, 60,  9, 74],
       [46, 18,  3, 41],
       [78, 68,  5, 59]])

In [104]:
np.mean(array_data)

np.float64(43.6875)

In [105]:
np.mean(array_data, axis=1)

array([36.  , 59.25, 27.  , 52.5 ])

In [107]:
np.mean(array_data, axis=0).astype("int")

array([57, 39, 24, 54])

In [108]:
np.std(array_data)

np.float64(29.943110121528793)

In [109]:
np.std(array_data, axis=1).astype("int")

array([28, 31, 17, 28])

In [117]:
np.mean(array_data, axis=1)

array([36.  , 59.25, 27.  , 52.5 ])

In [112]:
array_data

array([[10, 11, 81, 42],
       [94, 60,  9, 74],
       [46, 18,  3, 41],
       [78, 68,  5, 59]])

In [118]:
np.var(array_data, axis=0)

array([1035.    ,  626.6875, 1068.75  ,  184.5   ])

In [122]:
np.sin(0)

np.float64(0.0)

In [123]:
np.sin(90)

np.float64(0.8939966636005579)

In [120]:
np.tan(45)

np.float64(1.6197751905438615)

In [121]:
np.cos(90)

np.float64(-0.4480736161291701)

In [ ]:
arr1 = np.round(np.random.random((3,4)) * 10).astype("int")
arr2 = np.round(np.random.random((4,3)) * 10).astype("int")

In [137]:
arr1

array([[1, 4, 3, 2],
       [9, 7, 4, 6],
       [2, 5, 3, 1]])

In [135]:
arr2

array([[ 9,  6,  1],
       [ 4,  4,  1],
       [ 9,  2,  7],
       [10,  7,  1]])

In [138]:
np.dot(arr1, arr_2)

array([[234, 244, 254, 264],
       [574, 600, 626, 652],
       [243, 254, 265, 276]])

In [139]:
arr1

array([[1, 4, 3, 2],
       [9, 7, 4, 6],
       [2, 5, 3, 1]])

In [140]:
np.log(arr1)

array([[0.        , 1.38629436, 1.09861229, 0.69314718],
       [2.19722458, 1.94591015, 1.38629436, 1.79175947],
       [0.69314718, 1.60943791, 1.09861229, 0.        ]])

In [141]:
np.exp(arr1)

array([[2.71828183e+00, 5.45981500e+01, 2.00855369e+01, 7.38905610e+00],
       [8.10308393e+03, 1.09663316e+03, 5.45981500e+01, 4.03428793e+02],
       [7.38905610e+00, 1.48413159e+02, 2.00855369e+01, 2.71828183e+00]])

In [142]:
arr1

array([[1, 4, 3, 2],
       [9, 7, 4, 6],
       [2, 5, 3, 1]])

In [146]:
np.transpose(arr1)

array([[1, 9, 2],
       [4, 7, 5],
       [3, 4, 3],
       [2, 6, 1]])

In [149]:
np.ravel(arr1)

array([1, 4, 3, 2, 9, 7, 4, 6, 2, 5, 3, 1])

In [170]:
my_arr = np.round(np.random.random((5, 5)) * 100).astype("int32")
my_arr

array([[26, 91, 23,  1, 75],
       [32, 22, 39, 87, 17],
       [41, 50, 21, 60, 20],
       [31, 17, 25, 17, 23],
       [86, 99, 85, 78, 44]], dtype=int32)

In [175]:
my_arr[:, 2]

array([23, 39, 21, 25, 85], dtype=int32)

In [154]:
one_d = np.ravel(my_arr)
one_d

array([14, 58,  6, 14, 34, 48, 46, 33, 45, 22, 44, 85, 92, 17, 32, 80, 55,
        9,  9,  4, 42, 85,  8, 19, 72], dtype=int32)

In [156]:
one_d[2]

np.int32(6)

In [176]:
my_arr[3, 3]

np.int32(17)

In [161]:
three_new = np.arange(1, 9).reshape(2,2,2)
three_new

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
three_new[1, 0, 1]

np.int64(6)

In [177]:
my_arr

array([[26, 91, 23,  1, 75],
       [32, 22, 39, 87, 17],
       [41, 50, 21, 60, 20],
       [31, 17, 25, 17, 23],
       [86, 99, 85, 78, 44]], dtype=int32)

In [182]:
my_arr[2:5, 1:4]

array([[50, 21, 60],
       [17, 25, 17],
       [99, 85, 78]], dtype=int32)

In [185]:
for i in my_arr:
    print(i)

[26 91 23  1 75]
[32 22 39 87 17]
[41 50 21 60 20]
[31 17 25 17 23]
[86 99 85 78 44]


In [186]:
for i in np.nditer(my_arr):
    print(i)

26
91
23
1
75
32
22
39
87
17
41
50
21
60
20
31
17
25
17
23
86
99
85
78
44


In [188]:
arr1 = np.arange(1, 13).reshape(3,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [189]:
arr2 = np.arange(13, 25).reshape(3,4)
arr2

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [192]:
horizontal = np.hstack((arr1, arr2))
horizontal

array([[ 1,  2,  3,  4, 13, 14, 15, 16],
       [ 5,  6,  7,  8, 17, 18, 19, 20],
       [ 9, 10, 11, 12, 21, 22, 23, 24]])

In [193]:
vertical = np.vstack((arr1, arr2))
vertical

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [199]:
np.vsplit(vertical, 2)

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])]

In [200]:
np.hsplit(horizontal,2)

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])]